server:
  port: 8080
  servlet:
    context-path: /pro
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 10

queueName: publish.queue
topicName: publish.topic